---
- name: playbook1
  hosts: ios
  connection: local
  gather_facts: no
  tasks:
    - name: Task 1 showing the version
      ios_command: 
        commands: 
          - show run
        provider:
          hostname: projet2019
          password: projet2019
          host: "{{inventory_hostname}}"
          authorize: yes
          auth_pass: projet2019
